CREATE OR REPLACE TABLE USR_USER
(
    USER_KEY    BIGINT        NOT NULL PRIMARY KEY,
    USER_ID     VARCHAR(256)  NOT NULL UNIQUE,
    EMAIL       VARCHAR(256)  NOT NULL UNIQUE,
    NAME        VARCHAR(512)  NOT NULL,
    DELETED     BOOLEAN       NOT NULL,
    REASON      VARCHAR(1000) NOT NULL,
    CREATED_BY  BIGINT        NOT NULL,
    CREATED_AT  TIMESTAMP     NOT NULL,
    MODIFIED_BY BIGINT        NOT NULL,
    MODIFIED_AT TIMESTAMP     NOT NULL

) COLLATE = 'utf8mb4_general_ci'
  ENGINE = InnoDB;

CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;


CREATE OR REPLACE TABLE STD_STUDY
(
    STUDY_KEY   BIGINT        NOT NULL PRIMARY KEY,
    STUDY_ID    VARCHAR(256)  NOT NULL UNIQUE,
    NAME        VARCHAR(512)  NOT NULL,
    DELETED     BOOLEAN       NOT NULL,
    REASON      VARCHAR(1000) NOT NULL,
    CREATED_BY  BIGINT        NOT NULL,
    CREATED_AT  TIMESTAMP     NOT NULL,
    MODIFIED_BY BIGINT        NOT NULL,
    MODIFIED_AT TIMESTAMP     NOT NULL
) COLLATE = 'utf8mb4_general_ci'
  ENGINE = InnoDB;
CREATE SEQUENCE STUDY_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE STD_USER
(
    USER_KEY    BIGINT        NOT NULL,
    STUDY_KEY   BIGINT        NOT NULL,
    DELETED     BOOLEAN       NOT NULL,
    REASON      VARCHAR(1000) NOT NULL,
    CREATED_BY  BIGINT        NOT NULL,
    CREATED_AT  TIMESTAMP     NOT NULL,
    MODIFIED_BY BIGINT        NOT NULL,
    MODIFIED_AT TIMESTAMP     NOT NULL
);
ALTER TABLE STD_USER
    ADD PRIMARY KEY (USER_KEY, STUDY_KEY);

CREATE OR REPLACE TABLE REVINFO
(
    REV      BIGINT    NOT NULL,
    REVTSTMP TIMESTAMP NOT NULL
) COLLATE = 'utf8mb4_general_ci'
  ENGINE = InnoDB;
CREATE SEQUENCE REV_SEQ START WITH 1 INCREMENT BY 1;